# List of rules: https://docs.astral.sh/ruff/rules/
# List of settings: https://docs.astral.sh/ruff/settings/

# Exclude a variety of commonly ignored directories.
exclude = [
    "*_rc.py",
    "*_ui.py",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 120

[lint]    # for `ruff check`
select = [
    "E",    # pycodestyle errors (PEP8)
    "W",    # pycodestyle warnings
    "F",    # pyflakes (checks Python source files for errors)
    "I",    # isort is a Python utility to sort imports alphabetically and automatically separate into sections
    "N",    # pep8-naming conventions
]
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = [
    "F401",    # {name} imported but unused
    "F541",    # f-string without any placeholders
    "I",       # isort is a Python utility to sort imports alphabetically and automatically separate into sections
    "W291",    # Trailing whitespace
    "W292",    # No newline at end of file
    "W293",    # Blank line contains whitespace
]
unfixable = []

[lint.isort]
section-order = [
    "future",              # e.g. from __future__ import annotations
    "standard-library",    # e.g. import os
    "third-party",         # e.g. import numpy as np
    "python-qt",           # e.g. from PySide6.QtWidgets import QApplication
    "first-party",         # e.g. from my_project.utils import helper
    "local-folder",        # e.g. from .local_module import foo
]
[lint.isort.sections]
"python-qt" = ["PySide6", "PySide2"]


[format]    # for `ruff format`
# Ruff formatter is Black-compatible:
# - 4 spaces
# - no tabs
# - stable formatting
